version: "3"
 
services:
  postgres:
    container_name: db_obe
    image: 'postgres:13.6-alpine'
    environment:
      - POSTGRES_DB=one_bit_exchange
      - POSTGRES_USER=one_bit_exchange
      - POSTGRES_PASSWORD=one_bit_exchange
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
 
 
volumes:
  postgres:
  gems: