default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db_obe
  port: 5432
  username: one_bit_exchange
  password: one_bit_exchange

development:
  <<: *default
  database: one_bit_exchange_development

test:
  <<: *default
  database: one_bit_exchange_test

production:
  <<: *default
  database: one_bit_exchange_production
  password: <%= ENV['ONE_BIT_EXCHANGE_DATABASE_PASSWORD'] %>